// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwsipnswmjipeornoqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3c2lwbnN3bWppcGVvcm5vcXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjA1MTMsImV4cCI6MjA2MTUzNjUxM30.2Iz2Ks5BDumVT0NyELgD66kRXraXLdJVUK2aFvfjFgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);